### ISSUE TITLE
Container Minio

### ISSUE THREAD

**Issue by gmDarabas** [satc-disciplina-engenharia-de-dados/engenharia-dados#9]
Adicionar um container do minio do docker-compose para ser usado pelo apache spark

**Comment by Araldi42** [comment]
É um requisito obrigatório usar um bucket no projeto? Caso não sugiro usarmos o mongodb como nosso data lake. Vai facilitar nas integrações das ferramentas. A não ser que usemos um bucket em cloud.

**Comment by Araldi42** [comment]
Vi aqui que talvez fazer isso com mongo é somente na versão paga. Se for usar o MinIO tem que deixar ele bem redondo, na atividade do jorge o principal problema que tive com ele foi na integração. Temos que deixar isso redondinho então, provavelmente deixando Tudo em Docker.
